server:
  port: 8003
eureka:
  client:
    service-url:
      defaultZone: http://server2:7002/eureka/,http://server2:7002/eureka/,http://server3:7003/eureka/
  instance:
    prefer-ip-address: true
    instance-id: provider03

name: provider03